"""Generate ``assets/ascep-capacity-model.svg``, the README header figure for ASCEP.

The figure is generated by a script rather than drawn by hand so it can be regenerated
and diffed in review, and so a number in the figure cannot silently disagree with the
protocol it illustrates.

Stdlib only; the SVG is assembled as text so the output is byte-for-byte deterministic.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "assets" / "ascep-capacity-model.svg"

# Single quotes around the multi-word families, not double -- these strings land inside a
# double-quoted XML attribute, and a nested double quote closes it early. The whole document
# then fails to parse and the figure renders as a browser error page, not as a broken font.
FONT_SANS = (
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif"
)
FONT_MONO = "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace"

# Palette (baked light: the card is opaque white so GitHub dark mode cannot invert it).
INK = "#0F172A"
BODY = "#334155"
MUTED = "#64748B"
HAIRLINE = "#E2E8F0"
PANEL = "#F8FAFC"
ACCENT = "#2563EB"
BIND = "#B45309"
BINDFILL = "#FEF3C7"
GOOD = "#059669"
ANSWER_FILL = "#EFF6FF"
ANSWER_DIVIDER = "#BFDBFE"

# Illustrative numbers only: they show the shape of an ASCEP result, they are not a
# measurement from any campaign and must never be quoted as one.
KV_USERS = "12,400"
PREFILL_USERS = "3,100"
THROUGHPUT_USERS = "1,850"
TIER_NUMBERS = ("2,600", "1,850", "1,610", "1,400")

CANVAS_W = 1240
CANVAS_H = 680


def _esc(text: str) -> str:
    """Escape the three characters that would break XML text content."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _rect(
    x: float,
    y: float,
    w: float,
    h: float,
    rx: float,
    fill: str,
    stroke: str,
    stroke_width: float = 1,
    dash: str | None = None,
) -> str:
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{rx}" fill="{fill}"'
        f' stroke="{stroke}" stroke-width="{stroke_width}"{dash_attr}/>'
    )


def _text(
    x: float,
    y: float,
    content: str,
    size: float,
    fill: str,
    weight: int | None = None,
    family: str = FONT_SANS,
    anchor: str | None = None,
    letter_spacing: str | None = None,
    italic: bool = False,
) -> str:
    attrs = [f'x="{x}"', f'y="{y}"', f'font-family="{family}"', f'font-size="{size}"']
    if weight is not None:
        attrs.append(f'font-weight="{weight}"')
    if anchor is not None:
        attrs.append(f'text-anchor="{anchor}"')
    if letter_spacing is not None:
        attrs.append(f'letter-spacing="{letter_spacing}"')
    if italic:
        attrs.append('font-style="italic"')
    attrs.append(f'fill="{fill}"')
    return f"<text {' '.join(attrs)}>{_esc(content)}</text>"


def _chip(x: float, y: float, w: float, h: float, name: str, caption: str) -> list[str]:
    return [
        _rect(x, y, w, h, 8, PANEL, HAIRLINE),
        _text(x + 14, y + 20, name, 13, INK, weight=600),
        _text(x + 14, y + 36, caption, 10.5, MUTED),
    ]


def _arrow(x1: float, y1: float, x2: float, y2: float, color: str, width: float) -> str:
    """Line with a triangular head; only axis-aligned arrows are used in this figure."""
    dx, dy = x2 - x1, y2 - y1
    length = max(abs(dx), abs(dy))
    ux, uy = dx / length, dy / length
    # Head base sits 7px back from the tip so the tip lands exactly on (x2, y2).
    bx, by = x2 - ux * 7, y2 - uy * 7
    px, py = -uy * 4, ux * 4
    points = f"{x2},{y2} {bx + px},{by + py} {bx - px},{by - py}"
    return (
        f'<line x1="{x1}" y1="{y1}" x2="{bx}" y2="{by}" stroke="{color}"'
        f' stroke-width="{width}"/>'
        f'<polygon points="{points}" fill="{color}"/>'
    )


def _curve(x1: float, y1: float, x2: float, y2: float, color: str, width: float) -> str:
    """Quadratic converge curve; the control point keeps the line horizontal at its start
    so the eye reads it as leaving the source, not diving."""
    cx = (x1 + x2) / 2
    return (
        f'<path d="M {x1} {y1} Q {cx} {y1} {x2} {y2}" fill="none"'
        f' stroke="{color}" stroke-width="{width}"/>'
    )


def _section_label(x: float, y: float, label: str) -> str:
    return _text(x, y, label, 11, MUTED, weight=600, letter_spacing="0.10em")


def build_svg() -> str:
    parts: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS_W}" height="{CANVAS_H}"'
        f' viewBox="0 0 {CANVAS_W} {CANVAS_H}">',
        _rect(0, 0, CANVAS_W, CANVAS_H, 18, "#FFFFFF", HAIRLINE),
    ]

    # Title block.
    parts.append(
        _text(40, 52, "ASCEP — capacity is the minimum of four floors", 25, INK, weight=600)
    )
    parts.append(
        _text(
            40,
            80,
            "Declare it, measure it, and name the floor that binds — that is the number"
            " you can act on.",
            14.5,
            MUTED,
        )
    )

    # Section labels.
    parts.append(_section_label(40, 128, "DECLARE"))
    parts.append(_section_label(320, 128, "FOUR CAPACITY FLOORS"))
    parts.append(_section_label(900, 128, "THE ANSWER"))
    parts.append(_section_label(40, 528, "FOUR TIERS — THE SAME CLUSTER, FOUR HONEST ANSWERS"))

    # DECLARE band: five declaration chips.
    chips = [
        ("hardware", "GPU model, count, VRAM, interconnect"),
        ("model", "params, precision, KV geometry"),
        ("serving", "engine, TP/PP, max_model_len, KV dtype"),
        ("workload", "context shape, think time, SLO targets"),
        ("run", "ladder, windows, seeds, engine log"),
    ]
    chip_ys = [142 + i * 57 for i in range(5)]
    for (name, caption), cy in zip(chips, chip_ys, strict=True):
        parts.extend(_chip(40, cy, 232, 48, name, caption))
    # Hand-wrapped to stay inside the 232px column. SVG has no text wrapping, so a single
    # long line would run out from under the chips and straight through the SLO-gate box
    # at x=320 -- two overlapping sentences, not a clipped one.
    parts.append(_text(40, 444, "five JSON layers, schema-validated", 11, MUTED))
    parts.append(_text(40, 462, "a missing declaration refuses the run", 11, MUTED))
    parts.append(_text(40, 478, "before the first request", 11, MUTED))

    # Connector: each chip funnels into one accent arrow, so the eye sees five
    # declarations becoming one evaluation rather than five separate pipes.
    for cy in chip_ys:
        parts.append(_curve(272, cy + 24, 300, 268, HAIRLINE, 1))
    parts.append(_arrow(300, 268, 318, 268, ACCENT, 2))

    # FLOORS panel.
    parts.append(_rect(320, 142, 440, 276, 12, PANEL, HAIRLINE))
    rows = [
        # (name, formula, value, unit, fill, stroke, stroke_width, value_fill)
        ("Weights", "do the weights + a usable KV pool fit?", "fits ✓", None,
         "#FFFFFF", HAIRLINE, 1, GOOD),
        ("KV", "kv_tokens ÷ avg_context_tokens", KV_USERS, "users",
         "#FFFFFF", HAIRLINE, 1, INK),
        ("Prefill", "usable_prefill_tok_s ÷ prompt demand", PREFILL_USERS, "users",
         "#FFFFFF", HAIRLINE, 1, INK),
        ("Throughput", "usable_tok_s ÷ per-user demand", THROUGHPUT_USERS, "users",
         BINDFILL, BIND, 1.5, BIND),
    ]
    row_ys = [154 + i * 64 for i in range(4)]
    for (name, formula, value, unit, fill, stroke, sw, vfill), ry in zip(
        rows, row_ys, strict=True
    ):
        parts.append(_rect(332, ry, 416, 60, 8, fill, stroke, sw))
        parts.append(_text(348, ry + 24, name, 13.5, INK, weight=600))
        parts.append(_text(348, ry + 42, formula, 10.5, MUTED, family=FONT_MONO))
        if unit is None:
            parts.append(_text(732, ry + 32, value, 15, vfill, weight=700, anchor="end"))
        else:
            parts.append(_text(732, ry + 27, value, 17, vfill, weight=700, anchor="end"))
            parts.append(_text(732, ry + 42, unit, 10, vfill, anchor="end"))

    # SLO gate: dashed because it is a filter, not a floor — a rung that misses it
    # must not be allowed to read as capacity.
    parts.append(_rect(320, 436, 440, 42, 8, "#FFFFFF", HAIRLINE, dash="4 3"))
    parts.append(
        _text(336, 462, "SLO gate  ·  p95 TTFT ≤ 400 ms  ·  p95 TPOT ≤ 50 ms", 12, BODY)
    )
    parts.append(_arrow(540, 436, 540, 418, MUTED, 1.5))
    parts.append(
        _text(
            320,
            496,
            "a rung that misses the gate is not capacity — it is an overload",
            11,
            MUTED,
            italic=True,
        )
    )

    # min(): the three numeric floors converge; the binding one is drawn heavier and in
    # the bind colour so the answer's provenance is visible in the wiring itself.
    for cy in (248, 312):
        parts.append(_curve(748, cy, 790, 300, HAIRLINE, 1))
    parts.append(_curve(748, 376, 790, 300, BIND, 2))
    parts.append(_rect(790, 280, 76, 40, 20, "#FFFFFF", ACCENT, 1.5))
    parts.append(_text(828, 305, "min( )", 14, ACCENT, weight=600, anchor="middle"))
    parts.append(_arrow(866, 300, 896, 300, ACCENT, 2))

    # Answer card.
    parts.append(_rect(900, 142, 300, 190, 12, ANSWER_FILL, ACCENT, 1.5))
    parts.append(_text(920, 172, "CAPACITY", 11, ACCENT, weight=600, letter_spacing="0.10em"))
    parts.append(_text(920, 226, THROUGHPUT_USERS, 46, INK, weight=700))
    parts.append(_text(920, 250, "concurrent users, at the declared SLO", 12, BODY))
    parts.append(
        f'<line x1="920" y1="268" x2="1180" y2="268" stroke="{ANSWER_DIVIDER}" stroke-width="1"/>'
    )
    parts.append(
        _text(920, 290, "BINDING CONSTRAINT", 10, MUTED, weight=600, letter_spacing="0.08em")
    )
    parts.append(_text(920, 314, "throughput", 20, BIND, weight=700))
    for i, line in enumerate(
        [
            "A capacity number without its binding",
            "constraint does not tell you what to buy",
            "more of. ASCEP requires naming it.",
        ]
    ):
        parts.append(_text(900, 360 + i * 16, line, 11.5, MUTED))

    # FOUR TIERS band.
    tiers = [
        ("theoretical", TIER_NUMBERS[0], "roofline ceiling — what the silicon allows", "(U)"),
        ("measured", TIER_NUMBERS[1], "observed on the ladder, at the SLO gate", "(M)"),
        ("sustainable", TIER_NUMBERS[2], "held for ≥ 30 min without drift", "(M)"),
        ("recommended", TIER_NUMBERS[3], "sustainable ÷ 1.15 headroom", "(I)"),
    ]
    for i, (tier, number, under, tag) in enumerate(tiers):
        tx = 40 + i * 296
        is_measured = tier == "measured"
        parts.append(
            _rect(tx, 542, 272, 104, 10, "#FFFFFF", ACCENT if is_measured else HAIRLINE,
                  1.5 if is_measured else 1)
        )
        parts.append(
            _text(tx + 16, 568, tier.upper(), 12, MUTED, weight=600, letter_spacing="0.06em")
        )
        parts.append(
            _text(tx + 16, 606, number, 28, ACCENT if is_measured else INK, weight=700)
        )
        parts.append(_text(tx + 16, 628, under, 10.5, MUTED))
        parts.append(_rect(tx + 226, 556, 30, 18, 9, PANEL, HAIRLINE))
        parts.append(_text(tx + 241, 569, tag, 10, MUTED, weight=600, anchor="middle"))

    # Footer.
    parts.append(
        f'<line x1="40" y1="660" x2="1200" y2="660" stroke="{HAIRLINE}" stroke-width="1"/>'
    )
    parts.append(
        _text(
            40,
            676,
            "Every number carries provenance — (M) measured  ·  (I) inferred from measured"
            " inputs  ·  (U) unmeasured, with the reason  ·  graded against conformance"
            " rules C1–C12",
            10.5,
            MUTED,
        )
    )

    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="output path (default: assets/ascep-capacity-model.svg, resolved from the repo root)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and exit 1 if the file on disk differs",
    )
    args = parser.parse_args()

    svg = build_svg()

    if args.check:
        if not args.out.exists():
            print(f"MISSING: {args.out} (run tools/make_figure.py)")
            return 1
        on_disk = args.out.read_text(encoding="utf-8")
        if on_disk != svg:
            print(f"STALE: {args.out} (run tools/make_figure.py)")
            return 1
        print(f"OK: {args.out} is up to date")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(svg, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
